# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # (npm 5 bundled with node starting from version 8)
      - image: circleci/node:boron-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v7-dependencies-{{ checksum "package-lock.json" }}
            - v7-dependencies

      - run:
          name: Install local npm v5.3.0 if not in cache
          command: '[ -d temp/node_modules/npm ] && echo "cached npm@5.3.0 found" || npm install npm@5.3.0 --no-save --prefix ./temp'

      - run:
          name: Copy local npm v5 as global npm
          command: 'sudo rm -rf /usr/local/lib/node_modules/npm ; sudo cp -rf temp/node_modules/npm /usr/local/lib/node_modules/npm'

      - run: npm install

      - save_cache:
          key: v7-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - temp/node_modules

      - save_cache:
          key: v7-dependencies
          paths:
            - node_modules
            - temp/node_modules

      # run tests!
      - run: npm run test


