# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # (npm 5 bundled with node starting from version 8)
      - image: circleci/node:boron-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies


      - run:
          name: Install npm v5 locally
          command: npm install npm@5

      - run:
          name: Copy local npm v5 as global npm
          command: 'sudo rm -rf /usr/local/lib/node_modules/npm ; sudo cp -rf node_modules/npm /usr/local/lib/node_modules/npm'

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test:phantomjs


